CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE stores (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(50) NOT NULL,
  phone VARCHAR(50) NULL,
  coordenates VARCHAR(50) NULL,
  loc VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  state VARCHAR(50) NOT NULL,
  brand VARCHAR(50) NULL
);